Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2509
"GET /mailling/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/ HTTP/1.1" 404 2537
Not Found: /accounts/users/
"GET /accounts/users/ HTTP/1.1" 404 2521
Not Found: /users/
"GET /users/ HTTP/1.1" 404 3130
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users:login
"GET /users/login/ HTTP/1.1" 500 81624
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/login/ HTTP/1.1" 200 3636
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 145063
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
"GET /users/login/ HTTP/1.1" 200 3636
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
"GET /users/login/ HTTP/1.1" 200 3636
"GET /users/login/ HTTP/1.1" 200 3636
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3636
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3636
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3636
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /mailling/create/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/create/ HTTP/1.1" 404 2544
"GET /users/login/ HTTP/1.1" 200 3636
Not Found: /logout/
"POST /logout/ HTTP/1.1" 404 2498
"GET /users/login/ HTTP/1.1" 200 3636
"POST /users/login/ HTTP/1.1" 200 3943
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"GET /static/admin/css/base.css HTTP/1.1" 200 22092
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4336
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"GET /users/login/ HTTP/1.1" 200 3636
Not Found: /register/
"GET /register/ HTTP/1.1" 404 2503
"GET /users/register/ HTTP/1.1" 200 5881
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3642
"GET /users/register/ HTTP/1.1" 200 5887
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/register/ HTTP/1.1" 200 6030
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5887
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2494
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2494
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2494
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2494
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2494
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /mailling/create/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/create/ HTTP/1.1" 404 2544
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3958
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\models.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 200 3958
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3958
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "Z:\MyProjects\DjangoMailing\users\views.py", line 43, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 119, in get_success_url
    if self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '../templates/login.html' not found. '../templates/login.html' is not a valid view function or pattern name.
"POST /users/register/ HTTP/1.1" 500 115967
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/register/ HTTP/1.1" 200 6220
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3971
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "Z:\MyProjects\DjangoMailing\users\views.py", line 44, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 119, in get_success_url
    if self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '../templates/login.html' not found. '../templates/login.html' is not a valid view function or pattern name.
"POST /users/register/ HTTP/1.1" 500 115906
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/register/ HTTP/1.1" 200 5899
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3950
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4336
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3971
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/logout/ HTTP/1.1" 302 0
Not Found: /home/
"GET /home/ HTTP/1.1" 404 2491
"GET /users/login/ HTTP/1.1" 200 3654
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/register/ HTTP/1.1" 200 6077
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/register/ HTTP/1.1" 200 6077
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/register/ HTTP/1.1" 200 6279
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 3654
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3952
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3952
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"POST /users/login/ HTTP/1.1" 200 3952
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /mailling/create/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/create/ HTTP/1.1" 404 2544
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /users/register/ HTTP/1.1" 200 6018
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/password_reset/ HTTP/1.1" 200 4055
"GET /static/admin/css/forms.css HTTP/1.1" 200 8794
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
"GET /users/login/ HTTP/1.1" 200 3773
"GET /users/login/ HTTP/1.1" 200 3773
"GET /users/password_reset/ HTTP/1.1" 200 4055
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/register/ HTTP/1.1" 200 6018
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 3175
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/email-confirm/65e832506054d39ecb42c1e8ea470405/
"GET /users/email-confirm/65e832506054d39ecb42c1e8ea470405/ HTTP/1.1" 404 3271
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4328
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4337
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /mailling/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/ HTTP/1.1" 404 2537
"GET /users/register/ HTTP/1.1" 200 6441
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80639
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80582
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /users/password_reset/ HTTP/1.1" 200 3906
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password-reset/done/
"GET /users/password-reset/done/ HTTP/1.1" 404 4363
Not Found: /users/password-reset/done/
"GET /users/password-reset/done/ HTTP/1.1" 404 4363
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password_reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password_reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password_reset/done/
"GET /users/password_reset/done/ HTTP/1.1" 404 4363
"POST /users/password_reset/ HTTP/1.1" 302 0
"GET /users/password-reset/done/ HTTP/1.1" 200 3756
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 3952
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"POST /users/login/ HTTP/1.1" 200 3952
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/register/ HTTP/1.1" 200 5899
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /mailling/create/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/create/ HTTP/1.1" 404 2544
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /users/register/ HTTP/1.1" 200 6018
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/password_reset/ HTTP/1.1" 200 4055
"GET /static/admin/css/forms.css HTTP/1.1" 200 8794
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
"GET /users/login/ HTTP/1.1" 200 3773
"GET /users/login/ HTTP/1.1" 200 3773
"GET /users/password_reset/ HTTP/1.1" 200 4055
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 229, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\contrib\auth\views.py", line 243, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\views\generic\edit.py", line 57, in get_success_url
    if not self.success_url:
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
"POST /users/password_reset/ HTTP/1.1" 500 133852
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/register/ HTTP/1.1" 200 6018
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 3175
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/email-confirm/65e832506054d39ecb42c1e8ea470405/
"GET /users/email-confirm/65e832506054d39ecb42c1e8ea470405/ HTTP/1.1" 404 3271
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4328
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4337
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /mailling/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/mailling/ HTTP/1.1" 404 2537
"GET /users/register/ HTTP/1.1" 200 6441
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password_reset/
"GET /users/password_reset/ HTTP/1.1" 404 4348
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80639
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80582
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Internal Server Error: /users/password_reset/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../DjangoMailling/users/templates/password_reset_form.html
"GET /users/password_reset/ HTTP/1.1" 500 80839
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /users/password_reset/ HTTP/1.1" 200 3906
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password-reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password-reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password-reset/done/
"GET /users/password-reset/done/ HTTP/1.1" 404 4363
Not Found: /users/password-reset/done/
"GET /users/password-reset/done/ HTTP/1.1" 404 4363
"POST /users/password_reset/ HTTP/1.1" 302 0
Internal Server Error: /users/password_reset/done/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/password_reset_done.html
"GET /users/password_reset/done/ HTTP/1.1" 500 82384
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /users/password_reset/done/
"GET /users/password_reset/done/ HTTP/1.1" 404 4363
"POST /users/password_reset/ HTTP/1.1" 302 0
"GET /users/password-reset/done/ HTTP/1.1" 200 3756
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/password-reset/done/ HTTP/1.1" 200 4096
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/password_reset/ HTTP/1.1" 302 0
"GET /users/password-reset/done/ HTTP/1.1" 200 4096
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/password_reset/ HTTP/1.1" 302 0
"GET /users/password-reset/done/ HTTP/1.1" 200 4096
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/password_reset/ HTTP/1.1" 200 3906
"GET /users/password_reset/ HTTP/1.1" 200 3906
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/password_reset/ HTTP/1.1" 302 0
"GET /users/password-reset/done/ HTTP/1.1" 200 4096
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\mailling\views.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\mailling\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
"GET /users/register/ HTTP/1.1" 200 6441
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/login/ HTTP/1.1" 200 4196
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4486
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4486
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4489
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4489
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 200 4489
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4489
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4489
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4504
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4495
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/login/ HTTP/1.1" 200 4487
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2458
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2509
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"GET /users/ HTTP/1.1" 500 81659
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/templates/login.html
"GET /users/ HTTP/1.1" 500 81956
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/templates/login.html
"GET /users/ HTTP/1.1" 500 81956
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/templates/login.html
"GET /users/ HTTP/1.1" 500 81956
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: ../users/templates/login.html
"GET /users/ HTTP/1.1" 500 80298
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/ HTTP/1.1" 200 4196
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/ HTTP/1.1" 200 4495
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"POST /users/ HTTP/1.1" 500 82829
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/ HTTP/1.1" 200 4495
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/ HTTP/1.1" 200 4487
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Z:\MyProjects\DjangoMailing\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\conf\global_settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\conf\global_settings.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/ HTTP/1.1" 200 4487
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/password_reset/ HTTP/1.1" 200 3906
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Not Found: /users/login/
"GET /users/login/ HTTP/1.1" 404 4315
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krizh\AppData\Local\pypoetry\Cache\virtualenvs\djangomailing-Q0HN8ayx-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /users/login.html
"GET /users/ HTTP/1.1" 500 80062
Z:\MyProjects\DjangoMailing\users\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/ HTTP/1.1" 200 4196
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/ HTTP/1.1" 200 4495
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"POST /users/ HTTP/1.1" 200 4487
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /users/ HTTP/1.1" 200 4196
"GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 1892
"GET /mailling/create/ HTTP/1.1" 302 0
Not Found: /users/login/
"GET /users/login/?next=/mailling/create/ HTTP/1.1" 404 4338
Z:\MyProjects\DjangoMailing\users\apps.py changed, reloading.
Watching for file changes with StatReloader
Z:\MyProjects\DjangoMailing\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
